version: 2.1
orbs:
  node: circleci/node@1.1.6

workflows:
    build-and-test:
      jobs:
        - build-and-test

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Run install
          command: |
            npm install
      - run:
          name: Run Eslint
          command: |
            npm run lint
      - run:
          name: Run test
          command: |
            npm test
